### PR TITLE
feat: elasticsearch and sql compat

### PR DESCRIPTION
**Pull request by manjeshpv**
PR having the code compatiable with elasticsearch and sql.

Todo:
* need to run test cases, 

Please add your comments

https://github.com/manjeshpv/pxl-storage

### CODE REVIEW

**Comment by analog-nico** [comment]
Hey @manjeshpv , I am delighted that you worked on this major extension!

For better maintainability, however, I intentionally split up `pxl` and `pxl-mongodb` into two libraries so that different persistence layers can be provided through additional packages. FWIW, I would take your code and create the two separate packages `pxl-elasticsearch` and `pxl-sql`.

I definitely want to keep `pxl-mongodb`’s focus on MongoDB only. How would you like to proceed with your extension?

**Comment by manjeshpv** [comment]
I only used switch

https://github.com/manjeshpv/pxl-storage/blob/master/lib/index.js#L10

**Comment by analog-nico** [comment]
I like that you used `switch`!

Nonetheless, cramming everything into one package makes the architecture monolithic. Internally, the `switch` allows a nice modularization but there are more concerns to consider. A technical aspect for example is the fact that users of `pxl-storage` install all packages needed for all three database layers – whereas they only need one. A human aspect is that an issue opened in the GitHub repo always has to be categorized by the persistence layer used. I don’t have an Elasticsearch test environment nor deep knowledge of the database. So I have to forward the issue to you. Probably the same vice versa for MongoDB.

Separate GitHub repos will make both technical maintenance and human coordination much easier. Ideally, you would create `pxl-elasticsearch` and `pxl-sql` and I will happily link them in the README of both `pxl` and `pxl-mongodb`. The next best thing would be that you remove the mongodb part in your `pxl-storage` package and publish it separately. This way you would at least not need to update your package if I update `pxl-mongodb`.

What do you say?

**Comment by manjeshpv** [comment]
I feel we can create 2 new repos

**Comment by analog-nico** [comment]
Awesome!

I think it wouldn't make sense to create an organisation for the pxl family yet. So creating those packages in your personal GitHub space is the way to go I think.

Let me know if I can help you with anything I can help you with!

**Pull request closed without merging**
